title: Ryan M Restivo
logo: "/images/logo.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  CISSP, CISM
  <br><br>
  Leader-Follower, Technologist.
  <br><br>
  <a href="https://www.linkedin.com/in/ryan-m-restivo/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.youracclaim.com/users/ryan-restivo.f3505fe5/badges"> View My Certifications </a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
